### ISSUE TITLE
IK AttributeError: 'dict' object has no attribute 'matrix'

### ISSUE THREAD

**Issue by louisdehaybe** [neka-nat/kinpy#11]
Hello, 
Thanks for the tool! 

However, I have problems to run the IK function. 

I do the following:

`from scipy.spatial.transform import Rotation as R`
`import kinpy as kp`
```
r = R.from_matrix([[-1, 0, 0],
                   [0, 1, 0],
                   [0, 0, -1]])
pos = np.array([0.5 , 0., 0.])
```
`target = kp.transform.Transform(rot = r.as_quat(), pos= pos )`
`ik_sol = kp.ik.inverse_kinematics(chain, pose = target)`

where chain points to my urdf , which works since I manage to use the forward_kinematics function of kinpy.
The last line does not work, as I get the error  "AttributeError: 'dict' object has no attribute 'matrix' ".

I tried going into the ik.py file and changing tf.matrix() to tf["tool0"].matrix() (where tool0 is the name of my end effector). Then I do not get any error but I get completely wrong solutions, with values more than 10000. 

Could you help, please ?

**Comment by neka-nat** [comment]
Hi,
Thank you!
IK needs to use `SerialChain` class instead of `Chain` class.

```py
chain = kp.build_serial_chain_from_urdf(data, 'tool0')
th1 = np.random.rand(2)
tg = chain.forward_kinematics(th1)
th2 = chain.inverse_kinematics(tg)
```

**Comment by louisdehaybe** [comment]
Thanks for the quick answer !
