### ISSUE TITLE
Is the jacobian in body frame

### ISSUE THREAD

**Issue by JunzheJosephZhu** [neka-nat/kinpy#14]
Hi, I read the code for jacobian. It seems that the jacobian is in body frame. Is this correct?

**Comment by neka-nat** [comment]
Hi,
By "body frame" you mean the root link?

**Comment by JunzheJosephZhu** [comment]
No, let me put it this way:
It seems that right now the jacobian is the derivative of root link's coordinate expressed in end effector frame, with respect to the joint positions. Is this correct?

**Comment by neka-nat** [comment]
That's correct!
If you have any suggestions on implementation, please let me know.

**Comment by JunzheJosephZhu** [comment]
Thanks for the clarification! I'm just learning kinematics and trying to verify that my understanding of things is correct.
