### ISSUE TITLE
Can kinpy compute the gradient of reward with respect to the model parameters?

### ISSUE THREAD

**Issue by ZJP-c4cld** [neka-nat/kinpy#16]
My research interest is robustness of RL algorithms to environment parameters. I want to modify currents RL algorithms to make them achieve good performance when they are tested in environments with unfamilar parameters. (For example, an agent is trained in Cartpole environment with 1m pole. I want it achieve good performance in Cartpole environment with 3m pole.)
      To achieve this goal, I want to get the relationship between model parameter values and RL algorithm's performance (reward). As a result, I want to get the gradient of reward with respect to the model parameters.
      Mujoco simulator has applied in my experiments. But Mujoco simulator is not implemented by pure python. So I cannot get the the gradient of reward with respect to the model parameters. After searching in github, I notice that your code has the function of calculating FK, IK and jacobian, which gives me some hopes. ^_^
     So my queation is:
     Can kinpy compute the gradient of reward with respect to the model parameters? If so, how should I use it to achieve this goal?

**Comment by neka-nat** [comment]
Hi,
The following package looks good!
https://github.com/UM-ARM-Lab/pytorch_kinematics

**Comment by ZJP-c4cld** [comment]
@neka-nat Thank you for your reply ^_^
