### ISSUE TITLE
An "inconsistent version" problem about the pypi package

### ISSUE THREAD

**Issue by itechbear** [neka-nat/kinpy#7]
When I try to install the package via pypi, it complains that the version number is inconsistent with metadata. See the screenshot below. Not sure whether it points to the `project.toml` file.

![kinpy-version-issue](https://user-images.githubusercontent.com/3747635/108208775-6f207b00-7164-11eb-9106-c3ba99e9a5cf.png)

**Comment by neka-nat** [comment]
Thanks!
I fixed it.

**Comment by itechbear** [comment]
Thanks, I saw the new package on pypi.

Just be curious, is it possible to loosen the version requirement on `numpy` ? I have a project depending on `tensorflow` 2.3.1, which requires `numpy <1.19.0`, while `kinpy` requires `numpy > 1.19.5` . For some reasons, it is not feasible to update `tensorflow`  to latest version for now because its eco system is too complex. 

I know there's a compatibility issue of [`numpy` 1.19.4 on windows](https://github.com/numpy/numpy/issues/17726), however, it should not be a blocker.

**Comment by neka-nat** [comment]
Lowering the version of numpy is not a problem.
For example, does setting it to v1.18.0 solve the problem?

**Comment by itechbear** [comment]
v1.18.0 should be fine.

**Comment by neka-nat** [comment]
I fixed it!

**Comment by itechbear** [comment]
Great! Thank you!
